### ISSUE TITLE
old

### ISSUE THREAD

**Issue by majovec** [Driesboy/SurvivalGames#8]
tHis is very old plugin

**Comment by GoldishKirby** [comment]
He dint make this plugin this plugin was named FSurvival Games

**Comment by Driesboy** [comment]
yes i create now a new fork

**Comment by majovec** [comment]
and it would not do automatic recovery chests?

**Comment by Driesboy** [comment]
use my chest refill plugin for survival games

**Comment by majovec** [comment]
yes but not so there was always someone and he / cr reset but it could use to make it redefined itself
