### ISSUE TITLE
Game doesn't start after countdown

### ISSUE THREAD

**Issue by Xlecronia** [Driesboy/SurvivalGames#9]
After countdown, game doesn't start and players are stuck on their spawns. 

Using genisys (php7)

**Comment by Driesboy** [comment]
I will fix it soon

**Comment by TonyWAV** [comment]
is this fixed?

**Comment by Driesboy** [comment]
Yes
Op 3-mei-2016 12:17 schreef "TonyWAV" <notifications@github.com>:

**Comment by TonyWAV** [comment]
Dries please close this because it was already fixed

**Comment by Driesboy** [comment]
B

**Comment by Gabriel865** [comment]
deathmath ?

**Comment by Driesboy** [comment]
Ni
